[build-system]
requires = ["setuptools"]  # TODO(Ruben): does "wheel" need to be in here?
build-backend = "setuptools.build_meta"

[project]
name = "pykatex"  # TODO(Ruben): Capitalization?
version = "0.0.1"
description = "TODO"
readme = "README.md"
authors = [
  {name = "Ruben van Nieuwpoort", email = "ruben@vannieuwpoort.dev"},
]

